### ISSUE TITLE
Add "url" and/or "homepage" entry to package.json

### ISSUE THREAD

**Issue by Trott** [stduhpf/caritat#1]
Adding a "url" and/or "homepage" entry in the package.json would result in the version published to npm linking to this repository. (I had to do a little bit of guessing to find it!)

**Comment by aduh95** [comment]
Hum so I tried to be smart and use the shortcut URL decribed in https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository, but it looks like it didn't work (or at least, it's not showing on my side).
