### ISSUE TITLE
Encrypted ballot generated by the web ui doesn't contain author info

### ISSUE THREAD

**Issue by RaisinTen** [stduhpf/caritat#5]
The generated json contains only the following fields:

* `encryptedSecret`
* `data`

The `author` field is missing.

**Comment by aduh95** [comment]
FWIW we are using the git commit author, it's repeated in the JSON file for convenience but it has no implication on your vote. The web UI can't guess what is the name or the email address of the voter, so it's simpler easier to not include it.

Closing as won't fix, thanks for the report.

**Comment by RaisinTen** [comment]
> FWIW we are using the git commit author, it's repeated in the JSON file for convenience but it has no implication on your vote.

Ah thanks, good to know.

> The web UI can't guess what is the name or the email address of the voter, so it's simpler easier to not include it.

But there's a field for the author info, right?
```
author: undefined <undefined>
```
Should that be removed?

**Comment by aduh95** [comment]
> But there's a field for the author info, right?
> 
> ```
> author: undefined <undefined>
> ```
> 
> Should that be removed?

Yes good catch. It should at least be commented out, so it's clearer that it's not a very relevant info. It's too late for this vote though, I'd rather avoid pushing non-vote commits to that PR to fix the `ballot.yml` file.
